// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASm4CDb_B368ZhnNBN6YxycQPdhEDV1_E',
    appId: '1:452607076938:android:53d22b4672ffa1092354b3',
    messagingSenderId: '452607076938',
    projectId: 'leit-b3193',
    storageBucket: 'leit-b3193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpn3Dx6yh5iSu5F5zswBPQl6_fKozxEIU',
    appId: '1:452607076938:ios:cf8e002612563e312354b3',
    messagingSenderId: '452607076938',
    projectId: 'leit-b3193',
    storageBucket: 'leit-b3193.firebasestorage.app',
    androidClientId: '452607076938-pka2od60ubq5j50hcugo8lc2ai7r7ebl.apps.googleusercontent.com',
    iosClientId: '452607076938-m4k51o2lrdcbhsn90d14e5otknd0hrgj.apps.googleusercontent.com',
    iosBundleId: 'com.mahdi.leit',
  );

}